version: "3.9"
   
services:
  envoy:
    build:
      context: ../../../../.. # backend root directory
      dockerfile: module/chaos/serverexperimentation/rtds/integration/Dockerfile.envoy
    ports:
      - "10000:10000"
      - "9901:9901"
  test_runner:
    build:
      context: ../../../../.. # backend root directory
      dockerfile: module/chaos/serverexperimentation/rtds/integration/Dockerfile
    command: /test
    ports:
      - "9000:9000"
